///|
pub extend ArrayObject with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Binding with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend CacheStats with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Cell with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Command with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend CommandBody with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Completion with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend DictObject with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Ensemble with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Evaluation with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Expr with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Frame with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Handler with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Interpreter with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend ListObject with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend ParseCache with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend ParsedCommand with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Part with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Procedure with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend ScriptParser with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend ScriptProgram with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend State with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend TclError with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend TclValue with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend ValuePayload with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend VariableValue with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Word with @moonbitlang/core/debug.Debug::{to_repr}
