"""Original deterministic fixtures. Expected values come only from Tcl 8.6.15."""
cases=[]
def add(name, source):
    cases.append(dict(name=name,source=source))
for a in ['0','1','-3','2147483647','9007199254740993','123456789012345678901234567890','2.5']:
    for b in ['2','-3','0','0.5']:
        for op in ['+','-','*','/','%','==','!=','<','>=','&','|','^']:
            add(f'numeric-{a}-{op}-{b}',f'expr {{{a} {op} {b}}}')
for i,expression in enumerate([
    '0x1e+2','0b101 + 0o7','010','08','08.0','2**3**2','-2**2','2**-2',
    '-2**-3','(-1)**-3','0**-1','12345678901234567890 << 60',
    '-12345678901234567890 >> 5','~12345678901234567890',
    '2 + 3 * 4 > 12 && 4 << 1 == 8','0 && [error bad]','1 || [error bad]',
    '1 ? 2 : [error bad]','0 ? [error bad] : 3','false ? noSuch() : 2',
    '1 ? 2 : bareword','0 ? 1 : 1 ? 3 : 4','true','on','!off',
    '"0x03" eq "3"','0x03 eq 3','001 eq 1','001 == 1','"a" < "b"',
    '"a b" in {a {a b} c}','3 ni {1 2 3}','"001"','"abc"',
    'NaN == NaN','NaN != NaN','Inf > 100','-Inf + Inf','1.0/0','0.0/0.0',
    'abs(-12345678901234567890)','double(3)','int(-3.9)','entier(1e25)',
    'wide(18446744073709551617)','round(-1.5)','round(2.5)',
    'ceil(-1.1)','floor(-1.1)','sqrt(4)','sqrt(-1)','pow(2,3)',
    'sin(0)','cos(0)','atan2(0,1)','hypot(3,4)','log(1)','exp(0)',
    'log10(100)','fmod(-5,2)','min(3,1.5,-2)','max(12345678901234567890,3)',
    'abs()','bool(true)','bool(off)','bool(0.2)','int(Inf)','double(NaN)',
]):
    add(f'expression-{i}',f'expr {{{expression}}}')
programs = [
    ('lazy-side-effects','set x 0; expr {0 && [incr x]}; expr {1 || [incr x]}; expr {1 ? 3 : [incr x]}; set x'),
    ('eager-unbraced-expr','set x 0; expr 0 && [incr x]; set x'),
    ('no-injected-expression','set x {1+2}; catch {expr {$x * 3}}'),
    ('variable-braced','set {a b} 4; set x ${a b}'),
    ('variable-empty','set {} empty; set x ${}'),
    ('variable-array-braced','set a(x) 4; set x ${a(x)}'),
    ('array-index-variable','set i x; set a(x) 7; set x $a($i)'),
    ('array-index-command','set a(3) 8; set x $a([expr {1+2}])'),
    ('literal-brackets','list a]b ]'),
    ('nested-brackets','set x [list {]} {[}]; lindex $x 0'),
    ('expansion-variable','set xs {1 {2 3}}; list start {*}$xs end'),
    ('expansion-braced','list {*}{1 {2 3}} 4'),
    ('if-then','if {1} then {set x yes} else {error no}'),
    ('if-elseif','if {0} {error no} elseif {1} then {set x yes} else {error no}'),
    ('if-implicit-else','if {0} {error no} {set x yes}'),
    ('namespace-variable','namespace eval n {variable x 2; proc get {} {variable x; incr x}}; list [n::get] $::n::x'),
    ('namespace-lexical','namespace eval n {proc helper {} {return yes}; proc main {} {helper}}; namespace eval m {proc helper {} {return no}; n::main}'),
    ('namespace-fallback','set x 1; namespace eval n {set x 2}; list $x [info exists ::n::x]'),
    ('namespace-qualified','namespace eval n {set ::x 4; set y 5}; list $x $::n::y'),
    ('namespace-metadata','namespace eval a::b {}; list [namespace parent ::a::b] [namespace tail a::b] [namespace qualifiers a::b] [namespace exists a::b]'),
    ('namespace-delete','namespace eval a::b {variable x 2; proc f {} {return 3}}; namespace delete a; list [namespace exists a::b] [info exists ::a::b::x]'),
    ('namespace-code','namespace eval n {variable x 4; set code [namespace code {set x}]}; eval $::n::code'),
    ('global-link','set x 3; proc p {} {global x; incr x}; list [p] $x'),
    ('global-qualified','namespace eval n {variable x 2}; proc p {} {global ::n::x; incr x}; list [p] $::n::x'),
    ('upvar-scalar','proc change {name} {upvar 1 $name x; incr x}; proc p {} {set y 4; change y; return $y}; p'),
    ('upvar-array','proc change {name} {upvar 1 $name a; set a(x) 4}; proc p {} {change z; return $z(x)}; p'),
    ('upvar-element','proc change {name} {upvar 1 $name x; incr x}; set a(x) 4; change a(x); set a(x)'),
    ('upvar-recreate','proc p {} {upvar #0 x alias; unset alias; set alias 7}; set x 3; p; set x'),
    ('upvar-root','set x 2; upvar #0 x y; incr y; set x'),
    ('uplevel-relative','proc p {} {set x 3; q; return $x}; proc q {} {uplevel 1 {incr x}}; p'),
    ('uplevel-root','set x 2; proc p {} {set x 99; uplevel #0 {incr x}}; list [p] $x'),
    ('proc-introspection','proc p {a {b 2} args} {return $a}; list [info args p] [info default p b d] $d [info body p]'),
    ('rename-namespace','namespace eval a {variable x 3; proc p {} {variable x; return $x}}; rename a::p q; q'),
    ('array-empty','array set a {}; list [array exists a] [array size a] [info exists a]'),
    ('array-values','array set a {x 1 y 2}; set a(x) 3; list [array size a] [lsort [array names a]] $a(x)'),
    ('array-collision','set a 1; array set a {x 2}'),
    ('array-unset','array set a {x1 1 x2 2 y 3}; array unset a x*; list [array names a] $a(y)'),
    ('array-exact','array set a {* 1 abc 2}; array names a -exact *'),
    ('array-missing','list [array exists no] [array size no] [array names no] [array get no]'),
    ('incr-big','set n 9223372036854775807; incr n'),
    ('stdout','puts -nonewline hello; puts world; puts last; set x done'),
    ('lmap-control','lmap x {1 2 3 4 5} {if {$x == 2} {continue}; if {$x == 5} {break}; expr {$x * 2}}'),
    ('lset-nested','set v {{a b} {c d}}; lset v {1 0} X'),
    ('lset-append','set v {a b}; lset v end+1 c'),
    ('lset-root','set v {a b}; lset v {} c'),
    ('linsert-end','linsert {a b c} end X'),
    ('linsert-before-last','linsert {a b c} end-1 X'),
    ('lreplace-insert','lreplace {a b c} 1 0 X'),
    ('lreplace-beyond','lreplace {a b} 9 10 X'),
    ('lsearch-all','lsearch -all -inline -not -exact {a b a c} a'),
    ('lsearch-start','lsearch -start 2 {abc ax abc} a*'),
    ('lsort-big','lsort -integer {9007199254740993 -1 9007199254740992}'),
    ('lsort-index','lsort -integer -index 1 {{a 3} {b 1} {c 2}}'),
    ('lsort-unique','lsort -nocase -unique {B a A b c}'),
    ('lsort-command','proc cmp {a b} {expr {$b - $a}}; lsort -command cmp {1 4 2 3}'),
    ('dict-create','dict create a 1 b 2 a 3'),
    ('dict-nested-get','dict get {a {b {c 4}}} a b c'),
    ('dict-exists','list [dict exists {a 1} a] [dict exists {a 1} x] [dict exists {a 1} a b]'),
    ('dict-invalid','dict size {a 1 b}'),
    ('dict-keys-values','list [dict keys {x 1 y 2}] [dict values {x 1 y 2}] [dict size {x 1 x 2}]'),
    ('dict-merge','dict merge {a 1 b 2} {a 3 c 4}'),
    ('dict-replace-remove','dict remove [dict replace {a 1 b 2} a 4 c 3] b missing'),
    ('dict-set','dict set d a b 4; dict set d a c 5; set d'),
    ('dict-unset','set d {a {b 4 c 5}}; dict unset d a b; set d'),
    ('dict-incr','set d {a 9223372036854775807}; dict incr d a 2; set d'),
    ('dict-append','dict append d a x y; dict lappend d b {a b} c; set d'),
    ('dict-for','set out {}; dict for {k v} {a 1 b 2 c 3} {if {$v == 2} {continue}; lappend out $k $v}; set out'),
    ('dict-map','dict map {k v} {a 1 b 2} {set k ${k}x; expr {$v * 2}}'),
    ('dict-filter-key','dict filter {aa 1 ab 2 b 3} key a*'),
    ('dict-filter-value','dict filter {a 10 b 20 c 11} value 1*'),
    ('dict-filter-script','dict filter {a 1 b 2 c 3} script {k v} {expr {$v > 1}}'),
    ('dict-update','set d {a 1 b 2}; dict update d a x b y {incr x; unset y}; set d'),
    ('dict-update-error','set d {a 1}; catch {dict update d a x {incr x; error bad}}; set d'),
    ('dict-with','set d {a {x 1 y 2}}; dict with d a {incr x; unset y}; set d'),
    ('dict-with-delete','set d {x 1}; dict with d {unset d; incr x}; info exists d'),
    ('string-utf16','list [string length a😀中] [string range a😀中 1 2]'),
    ('string-empty-search','list [string first {} abc] [string last {} abc]'),
    ('string-search','list [string first bc abcabc 2] [string last bc abcabc 3]'),
    ('string-compare','list [string compare -nocase Ab aB] [string equal -length 2 abc abx]'),
    ('string-case','list [string tolower ABCDEF 1 3] [string toupper abcdef 2 end-1] [string totitle hELLO]'),
    ('string-trim','list [string trim {  a b  }] [string trimleft xxabc x] [string trimright abcyyy y]'),
    ('string-replace','list [string replace abcdef 2 3 XY] [string replace abc 9 10 X]'),
    ('string-repeat','list [string repeat ab 3] [string repeat x -2]'),
    ('string-reverse','string reverse abc中'),
    ('string-glob',r'list [string match {a[0-9]?*} a2xy] [string match -nocase A* abc] [string match {a\*} a*]'),
    ('string-map','list [string map {ab X a Y} abac] [string map -nocase {A x B y} aBc]'),
]
for name,source in programs:add(name,source)
for i,source in enumerate([
    'expr {9007199254740993 == 9007199254740992.0}',
    'expr {-9007199254740993 < -9007199254740992.0}',
    'expr {1 < 1.5}', 'expr {-1 > -1.5}', 'expr {1 > Inf}',
    'expr {100000000000000010.0}', 'expr {-0.0}', 'expr {bool({ true })}',
    'namespace eval n {variable x}; list [info exists ::n::x] [namespace which -variable ::n::x]',
    'set x 1; namespace eval n {namespace which -variable x}',
    'set x 1; unset x; namespace eval n {set x 2}; list [info exists ::x] [info exists ::n::x]',
    'namespace eval n {set x 1; unset x}; set x 2; namespace eval n {set x}',
    'set x 1; set y 2; upvar #0 x y',
    'proc p {} {set a 2; global a}; p',
    'set x 1; upvar #0 x y; proc p {} {global y; incr y}; list [p] $x $::y',
    'set a(x) 2; upvar #0 a(x) y; proc p {} {global y; incr y}; list [p] $a(x) $::y',
    'namespace eval n {upvar #0 x y; set y 4}; list $x $::n::y',
    'proc p {} {global x; set a 1; variable y; info locals}; p',
    'namespace eval n {variable x; info vars x}',
    'set x 2; namespace eval n {variable x; catch {set x}}',
    'namespace eval n {variable x; unset -nocomplain x}; namespace which -variable ::n::x',
    'lset a {} x',
    'set a {}; lset a 0 0 x',
    'namespace eval n {proc a {} {return 7}; proc b {} {a}}; rename n::b ::b; b',
    'dict with d {}',
    'set d {a 1}; dict update d a x {set d {z 2}; incr x}; set d',
    'set d {a {x 1}}; catch {dict with d a {dict unset d a}}; set d',
    'set name tea; set total 20; puts "$name: $total"',
    'namespace eval n {set x 3}; set y $:::n:::x',
    'set x --1; incr x',
    'set x +-1; incr x',
]):
    add(f'boundary-{i}',source)
for exponent in [-308,-100,-7,-6,-5,-4,-3,0,15,16,17,20,21,100,308]:
    for mantissa in ['1','-1','1.2345678901234567']:
        add(f'float-display-{mantissa}-{exponent}',f'expr {{{mantissa}e{exponent}}}')
for value in ['1e25','-1e25','1e100','-1e100','1.9999999999999998','-0.5']:
    add(f'float-entier-{value}',f'expr {{entier({value})}}')
for cls in ['integer','wideinteger','entier','double','boolean','true','false','list','digit','xdigit','space','ascii','alpha','alnum']:
    for value in ['','0','08','1.5','true','_','abc','4294967295','4294967296','18446744073709551615','18446744073709551616']:
        add(f'string-is-{cls}-{value}',f'string is {cls} -strict {{{value}}}')
assert len({case['name'] for case in cases})==len(cases)
